[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["Flo Kempenich <flo@kempenich.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyperclip = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
