### Left half = Peripheral
# Right half is Central (its nice!view shows BT profile/sleep; left screen is dead)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

### Sleep & Deep Sleep: 2 hours (overrides 'corne.conf')
## Sleep
CONFIG_ZMK_IDLE_TIMEOUT=7200000
## Deep Sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000
